os: linux
language: minimal
stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      language: node_js
      node_js: '12'
      script:
        - npm ci
        - npm run lint
    - stage: test
      language: node_js
      node_js: '12'
      script:
        - npm ci
        - npm run test
